website/views.py
from flask import Blueprint, redirect, render_template, request, flash, jsonify, url_for, session
from flask_login import login_required, current_user
from .models import Item, Category
from . import db
import json
from bs4 import BeautifulSoup
import requests

views = Blueprint("views", __name__)

@views.route('/', methods=["GET", "POST"])
@login_required
def home():
    items = current_user.items

    filters = [category.name for category in Category.query.all()]
    filter = request.args.get("filter")
    if filter:
        items = [item for item in items if str(filter) in [category.name for category in item.categories]]

    page = request.args.get("page", 1, type=int)
    page_size = 8
    start = (page - 1) * page_size
    end = start + page_size
    pages = (len(items) + page_size - 1) // page_size
    page_items = items[start:end]
    
    return render_template(
        "home.html",
        user=current_user,
        items=page_items,
        page=page,
        pages=pages,
        filter=filter,
        filters=filters
    )

@views.route("/add-item", methods=["GET", "POST"])
def add_item():
    if request.method == "POST":
        item_name = request.form.get("item_name")
        price = request.form.get("price")
        category_names = request.form.get("categories").split(",")

        if len(item_name) < 1:
            flash("Item name must be set.", category="error")
        elif not price.replace(".", "", 1).isdigit():
            flash("Price must be a valid number.", category="error")
        else:
            item = Item.query.filter_by(name=item_name).first()
            if item:
                flash("Item already exists.", category="error")
            else:
                new_item = Item(name=item_name, price=price, user_id=current_user.id)
                db.session.add(new_item)
                item = new_item
                flash("Item added.", category="success")

            for category_name in category_names:
                if category_name != "":
                    category = Category.query.filter_by(name=category_name).first()
                    if category:
                        print(f"{category_name} already exists.")
                    else:
                        print(f"{category_name} must first be created.")
                        new_category = Category(name=category_name)
                        db.session.add(new_category)
                        category = new_category
                    item.categories.append(category)

            db.session.commit()
            return redirect(url_for("views.home"))
            
    return render_template(
        "add_item.html", 
        user=current_user,
        item_url=session["item_url"] if "item_url" in session else "",
        item_name=session["item_name"] if "item_name" in session else "",
        item_price=session["item_price"] if "item_price" in session else ""
    )

@views.route("/delete-item", methods=["POST"])
def delete_item():
    if request.method == "POST":
        item = json.loads(request.data)
        id = item["itemId"]
        item = Item.query.get(id)
        if item:
            if item.user_id == current_user.id:
                db.session.delete(item)
                db.session.commit()
                flash("Item deleted.", category="success")
            else:
                flash("You do not own this item.", category="error")
        else:
            flash("Item does not exist.", category="error")

        return jsonify({})

@views.route("/find-item", methods=["POST"])
def find_item():
    if request.method == "POST":
        data = json.loads(request.data)
        url = data["url"]

        if len(url) < 1:
            flash("URL must be set.", category="error")
        else:
            try:
                result = requests.get(url)
                doc = BeautifulSoup(result.text, "html.parser")

                item_name = doc.find("h1")
                prices = doc.find_all(text="£") + doc.find_all(text="$")
                price = prices[0].parent.find("strong") if prices else None

                print("Scraping web...")

                session["item_url"] = url
                session["item_name"] = "balls"
                session["item_price"] = 3
            except:
                flash("Invalid URL.", category="error")

            return redirect(url_for("views.add_item"))
        
        return jsonify({})

@views.route("/edit-item", methods=["GET", "POST"])
def edit_item():
    if request.method == "POST":
        item_id = request.args.get("id")
        item_name = request.form.get("item_name")
        price = request.form.get("price")
        url = request.form.get("url")
        categories = request.form.get("categories").split(",")

        item = Item.query.get(int(item_id))
        if item:
            if item.user_id == current_user.id:
                item.name = item_name
                item.price = price
                item.url = url

                for category_name in categories:
                    if category_name not in [category.name for category in item.categories] and category_name != "":
                        category = Category.query.filter_by(name=category_name).first()
                        if category:
                            print(f"{category_name} already exists.")
                        else:
                            print(f"{category_name} must first be created.")
                            new_category = Category(name=category_name)
                            db.session.add(new_category)
                            category = new_category
                        item.categories.append(category)

                for category in item.categories:
                    if category.name not in categories:
                        item.categories.remove(category)

                db.session.commit()
                flash("Item updated.", category="success")
                return redirect(url_for('views.home'))
            else:
                flash("You do not own this item.", category="error")
        else:
            flash("Item does not exist.", category="error")

    item_id = request.args.get("id")
    item = Item.query.get(item_id)
    return render_template("edit_item.html", user=current_user, item=item)

website/templates/add_item.html
{% extends "base.html" %}

{% block title %}Add item{% endblock %}

{% block content %}
<h3 align="center">Add new item</h3>
<form method="POST" class="col-4 offset-md-4">
    <label for="url">URL</label>
    <div class="d-flex mb-2">
        <input type="text" id="url" name="url" class="form-control" placeholder="Item URL"/>
        <button type="button" class="btn btn-primary bi-search ms-2"></button>
    </div>
    <div class="d-flex" style="align-items:center;">
        <div class="border-top w-50 me-2"></div>
        OR
        <div class="border-top w-50 ms-2"></div>
    </div>
    <label for="item_name">Name</label>
    <input type="text" id="item_name" name="item_name" class="form-control mb-2" placeholder="New item"/>
    <label for="price">Price</label>
    <div class="input-group mb-2">
        <span class="input-group-text">$</span>
        <input type="text" id="price" name="price" class="form-control" placeholder="0.00">
    </div>
    <label for="categories">Categories (press [Space] to add tag)</label>
    <input type="text" id="categories" name="categories" style="display:none"/>
    <div class="tag-box">
        <ul class="border p-2 rounded" id="ul-tags">
            <input class="form-control-tag mx-1" type="text" placeholder="Category" onkeypress="addCategory(event)" onkeyup="checkInput(event)">
        </ul>
    </div>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Add</button>
    </div>
</form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html data-bs-theme="dark">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link 
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
            rel="stylesheet" 
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
            crossorigin="anonymous"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}" />

        <title>{% block title %}Home{% endblock %}</title>
    </head>

    <body class="container-sm">
        <nav class="navbar navbar-expand-lg">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="login" href="/">Home</a>
                    <a class="nav-item nav-link" id="login" href="/logout">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" id="login" href="/sign-up">Sign up</a>
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == "success" %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% elif category == "error" %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}
                {% endfor%}
            {% endif %}
        {% endwith %}

        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <script 
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
            crossorigin="anonymous">
        </script>

        <script
            type="text/javascript"
            src="{{ url_for('static', filename='index.js') }}">
        </script>
    </body>
</html>

website/templates/edit_item.html
{% extends "base.html" %}

{% block title %}Edit item{% endblock %}

{% block content %}
<h3 align="center">Edit {{ item.name }}</h3>
<form method="POST" class="col-4 offset-md-4">
    <label for="item_name">Name</label>
    <input type="text" id="item_name" name="item_name" class="form-control mb-2" placeholder="New item" value="{{ item.name }}"/>
    <label for="price">Price</label>    
    <div class="input-group mb-2">
        <span class="input-group-text">$</span>
        <input type="text" id="price" name="price" class="form-control" placeholder="0.00" value="{{ item.price }}">
    </div>
    <label for="url">URL</label>
    <input 
        type="text" 
        id="url" 
        name="url" 
        class="form-control mb-2" 
        placeholder="Item URL" 
        value={% if item.url %}"{{ item.url }}"{% else %}""{% endif %}/>
    <label for="categories">Categories (press [Space] to add tag)</label>
    <input type="text" id="categories" name="categories" style="display:none"/>
    <div class="tag-box">
        <ul class="border p-2 rounded" id="ul-tags">
            {% for category in item.categories %}
            <li>
                <span class="badge text-bg-light mx-1">
                    {{ category.name }}
                    <button type="button" class="btn-transparent" onclick="removeCategory(this, '{{ category.name }}')">&times;</button>
                </span>
            </li>
            {% endfor %}
            <input class="form-control-tag mx-1" type="text" placeholder="Category" onkeypress="addCategory(event)" onkeyup="checkInput(event)">
        </ul>
    </div>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h3 align="center" class="mb-3">{{ user.username }}'s wishlist</h3>
<div class="col-6 offset-md-3">
    <div class="dropdown mb-2" align="right">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if filter == None %}All{% else %}{{ filter }}{% endif %}
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="{{ url_for('views.home') }}">All</a></li>
            {% for filter in filters %}
            <li><a class="dropdown-item" href="{{ url_for('views.home', filter=filter) }}">{{ filter }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <ul class="list-group mb-2" id="items">
        {% if items %}
            {% for item in items %}
            <li class="list-group-item justify-content-between d-flex" style="align-items:center;">
                <div class="d-inline-block" style="align-items:center;">
                    {{ item.name }} &middot; 
                    ${{ item.price}} &middot; 
                    <div class="d-inline-flex flex-wrap">
                    {% for category in item.categories %}
                    <span class="badge text-bg-light mx-1" style="height:20px;overflow:none;">{{ category.name }}</span>
                    {% endfor %}
                    </div>
                </div>
                <div class="d-flex">
                    <button type="button" class="btn btn-info bi-pencil mx-1" onclick="window.location.href='{{ url_for('views.edit_item', id=item.id) }}';"></button>
                    <button type="button" class="btn btn-danger bi-trash mx-1" onclick="deleteItem({{ item.id }})"></button>
                </div>
            </li>
            {% endfor %}
        {% else %}
        <li class="list-group-item justify-content-between d-flex" style="align-items:center;">
            <div class="d-flex" style="align-items:center;">
                No items to show.
            </div>
        </li>
        {% endif %}
    </ul>
    <div class="d-flex justify-content-between">
        <a type="submit" href="{{ url_for('views.add_item') }}" class="btn btn-primary" style="height:40px;">New item +</a>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class={% if page > 1 %}"page-item"{% else %}"page-item disabled"{% endif %}>
                    <a class="page-link" href="{{ url_for("views.home", page=page-1) }}">Previous</a>
                </li>
                {% if page > 1%}
                <li class="page-item"><a class="page-link" href="{{ url_for("views.home", page=page-1) }}">{{ page - 1 }}</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="#">{{ page }}</a></li>
                {% if page < pages %}
                <li class="page-item"><a class="page-link" href="{{ url_for("views.home", page=page+1) }}">{{ page + 1}}</a></li>
                {% endif %}
                <li class={% if page < pages %}"page-item"{% else %}"page-item disabled"{% endif %}>
                    <a class="page-link" href="{{ url_for("views.home", page=page+1) }}">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="POST" class="col-4 offset-md-4">
    <h3 align="center">Login</h1>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control mb-2" id="username" name="username" placeholder="Enter username..."/>
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="********"/>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
<form method="POST" class="col-4 offset-md-4">
    <h3 align="center">Sign up</h1>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control mb-2" id="username" name="username" placeholder="Enter username..."/>
        <label for="password1">Password</label>
        <input type="password" class="form-control mb-2" id="password1" name="password1" placeholder="********"/>
        <label for="password2">Confirm password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="********"/>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Sign up</button>
</form>
{% endblock %}